import { Metadata } from 'next';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Bot, Shield, Heart, ArrowRight } from 'lucide-react';

export const metadata: Metadata = {
  title: 'About',
  description: 'Learn about Grothi - our mission to make AI marketing accessible, ethical, and effective for everyone.',
};

export default function AboutPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur">
        <div className="container mx-auto flex h-16 items-center justify-between px-4">
          <Link href="/" className="flex items-center space-x-2">
            <Bot className="h-8 w-8 text-primary" />
            <span className="text-xl font-bold">Grothi</span>
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link href="/features" className="text-sm text-muted-foreground hover:text-foreground">Features</Link>
            <Link href="/pricing" className="text-sm text-muted-foreground hover:text-foreground">Pricing</Link>
            <Link href="/about" className="text-sm font-medium">About</Link>
            <Link href="/faq" className="text-sm text-muted-foreground hover:text-foreground">FAQ</Link>
          </nav>
          <div className="flex items-center space-x-3">
            <Link href="/auth/signin"><Button variant="ghost" size="sm">Sign In</Button></Link>
            <Link href="/auth/signup"><Button size="sm">Get Started</Button></Link>
          </div>
        </div>
      </header>

      <main className="flex-1">
        <section className="py-16 text-center">
          <h1 className="text-4xl font-bold">About Grothi</h1>
          <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
            AI-Powered Marketing on Autopilot
          </p>
        </section>

        <section className="pb-20 px-4 max-w-3xl mx-auto space-y-12">
          <div>
            <h2 className="text-2xl font-bold mb-4">Our Mission</h2>
            <p className="text-muted-foreground leading-relaxed">
              We believe every business deserves access to powerful AI marketing tools. Grothi makes it possible
              to create a self-learning marketing bot that works 24/7, posting engaging content across
              all your social media platforms while maintaining the highest ethical standards.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Shield className="h-6 w-6 text-secondary" /> White-Hat Only
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Every piece of content generated by Grothi bots goes through Constitutional AI safety
              guardrails. We enforce white-hat marketing practices, protect your brand reputation, and
              automatically detect and prevent any actions that could lead to account suspensions.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Heart className="h-6 w-6 text-destructive" /> Built with Care
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Grothi was born from real-world experience running AI marketing bots. We know what works,
              what gets you banned, and how to navigate the complex landscape of social media automation.
              Our platform encapsulates years of learning into a tool anyone can use.
            </p>
          </div>
        </section>

        <section className="py-16 text-center bg-primary/5 px-4">
          <h2 className="text-2xl font-bold">Ready to try it?</h2>
          <Link href="/auth/signup">
            <Button size="lg" className="mt-6">
              Get Started Free <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </Link>
        </section>
      </main>

      <footer className="border-t py-8 text-center text-sm text-muted-foreground">
        &copy; {new Date().getFullYear()} Grothi. All rights reserved.
      </footer>
    </div>
  );
}
