import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { verifyClickSignature } from '@/lib/email';

/**
 * GET /api/email/track/click?sid=<sendId>&url=<destinationUrl>&sig=<hmac>
 *
 * Records the click event and redirects to the destination URL.
 *
 * SECURITY — Open Redirect Prevention (CWE-601):
 * Without signature validation this endpoint could be used as an open
 * redirector: /api/email/track/click?url=https://phishing.com
 * All URLs generated by wrapLinksForTracking() carry a 16-char HMAC-SHA256
 * signature over (sendId + url). Unsigned or tampered URLs are rejected.
 */
export async function GET(request: NextRequest) {
  const sendId = request.nextUrl.searchParams.get('sid');
  const url = request.nextUrl.searchParams.get('url');
  const sig = request.nextUrl.searchParams.get('sig');

  if (!url) {
    return new NextResponse('Missing URL', { status: 400 });
  }

  // Validate URL structure and protocol
  let destinationUrl: URL;
  try {
    destinationUrl = new URL(url);
    if (!['http:', 'https:'].includes(destinationUrl.protocol)) {
      return new NextResponse('Invalid URL protocol', { status: 400 });
    }
  } catch {
    return new NextResponse('Invalid URL', { status: 400 });
  }

  // HMAC signature check — prevents open-redirect abuse.
  // Every click URL produced by wrapLinksForTracking() carries a valid `sig`.
  // Manually crafted or tampered links will fail here.
  if (!sendId || !sig || !verifyClickSignature(sendId, url, sig)) {
    return new NextResponse(
      `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
      <title>Invalid Link</title>
      <style>body{font-family:sans-serif;display:flex;justify-content:center;align-items:center;
      height:100vh;margin:0;background:#f9fafb;}
      .box{background:#fff;border-radius:12px;padding:40px;max-width:400px;
      text-align:center;box-shadow:0 1px 3px rgba(0,0,0,.1);}
      h1{font-size:1.2rem;margin:0 0 8px;}p{color:#555;font-size:14px;line-height:1.5;}</style>
      </head><body><div class="box">
      <h1>Invalid Link</h1>
      <p>This link could not be verified. It may be expired or invalid.</p>
      <p>If you received this in an email from Grothi, please contact support.</p>
      </div></body></html>`,
      { status: 400, headers: { 'Content-Type': 'text/html; charset=utf-8' } },
    );
  }

  // Track the click event
  try {
    const send = await db.emailSend.findUnique({ where: { id: sendId } });

    if (send) {
      if (!send.clickedAt) {
        await db.emailSend.update({
          where: { id: sendId },
          data: { status: 'CLICKED', clickedAt: new Date() },
        });
      }

      await db.emailEvent.create({
        data: {
          sendId,
          contactId: send.contactId,
          type: 'CLICKED',
          data: { url: destinationUrl.toString() },
          ip: request.headers.get('x-forwarded-for') || request.headers.get('x-real-ip') || null,
          userAgent: request.headers.get('user-agent') || null,
        },
      });

      await db.emailContact.update({
        where: { id: send.contactId },
        data: { lastClickAt: new Date(), clickCount: { increment: 1 } },
      });

      await db.emailCampaign.update({
        where: { id: send.campaignId },
        data: { totalClicked: { increment: 1 } },
      });
    }
  } catch {
    // Silently fail — still redirect on tracking errors
  }

  return NextResponse.redirect(destinationUrl.toString(), 302);
}
